<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of exception types with their corresponding custom log levels.
     *
     * @var array<class-string<\Throwable>, \Psr\Log\LogLevel::*>
     */
    protected $levels = [
        //
    ];

    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<\Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function report(Throwable $e)
    {
        return parent::report($e); // TODO: Change the autogenerated stub
    }

    public function render($request, Throwable $e)
    {
        if(\App::hasDebugModeEnabled()){
            return parent::render($request, $e);
        }
        if ($this->isHttpException($e)) {
            $message = $e->getMessage();
            if($e->getStatusCode() == 404){
                $message = 'The page you are requesting does not exist';
            }
            return response()->view('errors.http', [
                'code' => $e->getStatusCode(),
                'message' => $message
            ], $e->getStatusCode());
        }else{
            return response()->view('errors.application', [
                'message' => $e->getMessage()
            ], 500);
        }

        return parent::render($request, $e);
    }
}
